name: A Digital Dad
title: A Digital Dad | Productivity, Security, Knowledge for your online world.
description: Jekflix is a template for Jekyll inspired by Netflix and made by Thiago Rossener.
tags:
  - blog
  - digital
  - security
  - safety
  - online
  - dad
  - parenting
  - service
  - productivity
email: info@adigitaldad.com
disqus_username: a-digital-dad
show_hero: true
